### PR TITLE
Create schrodinger.md

### PR DESCRIPTION
**Pull request by mpiercy**

### CODE REVIEW

**Comment by mpiercy** [comment]
I don't see any spelling errors, yet I got : "check / spellcheck (pull_request_target) Failing after 14s" ?

**Comment by kcgthb** [comment]
> I don't see any spelling errors, yet I got : "check / spellcheck (pull_request_target) Failing after 14s" ?

The test seems to have a problem, I'll check it, but it's probably safe to ignore for now.

On the other hand, the new file won't appear on the rendered website unless it's also added to the navigation tree in the `mkdocs.yml` file, in the `nav:` section, like all the other pages. You can add it somewhere under "Software > Usage", like `docs/software/using/quantum-espresso.md` for instance.

**Comment by mpiercy** [comment]
I can't edit mkdocs.yml.  I get "you must be on a branch to make or propose changes to this file". So do I need to fork my own version of mkdocs.yml and create a new branch of www.sherlock.stanford.edu to add the line:

- Schrodinger. : docs/software/using/schrodinger.md
to line 290 in mkdocs.yml ??

**Comment by kcgthb** [comment]
Yes, you should be able to edit it in the same branch that you've created the new `schrodinger.md` file. 

But I can take it from there if you want, the most important part was the contents, I can handle the remaining bits, no worries. :)

**Review by kcgthb — APPROVED** [review]

**Pull request merged**
