### PR TITLE
Update prerequisites.md

### PR DESCRIPTION
**Pull request by mpiercy**

### CODE REVIEW

**Comment by mpiercy** [comment]
yes for now anyone with SUNet can look at it

________________________________

**Comment by mpiercy** [comment]
so will this get added to the page? or because its in /private (SUNetID required)  it wont get added?

**Comment by mpiercy** [comment]
it uses Farmshare (rice) but all concepts are applicable to Sherlock , so it's a decent on-boarding tool for novice Sherlock users.  It will continue to evolve and improve

**Comment by kcgthb** [comment]
I mean it's a great resource to have, but I was wondering why it had to be restricted to Stanford users only? Especially since it's based on an open HPC Carpentry course? Wouldn't it be better to have it available to everyone?

**Comment by kcgthb** [comment]
Maybe we could directly link to https://hpc-carpentry.github.io/hpc-intro/ ?

**Comment by vsoch** [comment]
+1 I agree with @kcgthb - I noticed that a lot of our older site tutorial content was directly copy pasta-d from HPC carpentry, and (other than feeling kind of wrong to copy it) it means that we would need to maintain it as opposed to using the community maintained resource. It's misleading to suggest that our group put together the content when it's largely not the case.

**Comment by mpiercy** [comment]
the one on SRCC uses **farmshare** so **Stanford** people, who are our users after all can use farmshare (all examples work on rice...) and follow along.   
Also, it's not wrong at all to copy the curriculum, it's actually encouraged.  It also says "based on the Carpentry GitHub page" with a **link** to it in the SRCC page.  We restrict sign up to the course to Stanford people only because Carpentries classes ALWAYS have non Stanford people try to take the courses (they see the listing on events.stanford.edu)  and we are not here to teach people outside of Stanford for free, since the courses are free to all Stanford people.  But never mind, leave the link it out, it should not be on the Sherlock page.

**Pull request closed without merging**
