### PR TITLE
Update filesystems.md

### PR DESCRIPTION
**Pull request by mpiercy**
adding more purge policy clarification see ticket https://srcc.freshdesk.com/a/tickets/42941

### CODE REVIEW

**Review by kcgthb — COMMENTED** [review]
I feel this is detailed in the [Expiration policy](https://www.sherlock.stanford.edu/docs/storage/filesystems/#expiration-policy) already?

**Comment by mpiercy** [comment]
ok, ignore

**Comment by vsoch** [comment]
I think redundancy doesn't hurt. If there is more information on this in another section and @kcgthb you don't want to have redundancy in the docs, perhaps there should be a link here to that section, since the user might not find the other one?

**Comment by kcgthb** [comment]
There is one link to the "Expiration policy" section, actually.
But redundancy doesn't hurt indeed, this is a pretty important topic.

**Review by kcgthb — APPROVED** [review]

**Comment by kcgthb** [comment]
Change in, thanks @mpiercy!

**Pull request merged**
