### PR TITLE
Update matlab.md

### PR DESCRIPTION
**Pull request by mpiercy**
better syntax

### CODE REVIEW

**Comment by kcgthb** [comment]
Maybe `-batch` would be an even better alternative?
https://www.mathworks.com/help/matlab/ref/matlablinux.html

**Comment by mpiercy** [comment]
If you can get -batch to work please add it to the example otherwise we can use
matlab -nodisplay -nosplash < parfor.m

**Comment by kcgthb** [comment]
That should work, right?
```
$ cat myscript.m
disp('Hello!')
```
```
$ matlab -batch 'myscript'
MATLAB is selecting SOFTWARE OPENGL rendering.
Hello!
```

**Comment by mpiercy** [comment]
[mpiercy@sh02-01n57 ~/sbatch_examples] (job 52575641) $ matlab -batch  'parfor'
 parfor
 |
Error: This statement is incomplete.

however this works:

[mpiercy@sh02-01n57 ~/sbatch_examples] (job 52575641) $ matlab -nodisplay -nosplash < parfor.m

                            < M A T L A B (R) >
                  Copyright 1984-2020 The MathWorks, Inc.
              R2020a Update 4 (9.8.0.1417392) 64-bit (glnxa64)
                               June 24, 2020

 
To get started, type doc.
For product information, visit www.mathworks.com.
 
>> >> >> >> Starting parallel pool (parpool) using the 'local' profile ...

**Comment by kcgthb** [comment]
Ah yes, I think that `parfor` is a reserved function name, so that's probably not the best choice for a script name, my bad.

**Comment by mpiercy** [comment]
I ll fix it in another PR ,

Thanks!

**Pull request closed without merging**
