### PR TITLE
remove python info

### PR DESCRIPTION
**Pull request by mpiercy**
whoops python got through!

### CODE REVIEW

**Comment by vsoch** [comment]
This seems like the gods are trying to send us a message...

**Comment by vsoch** [comment]
What's that, gods? You think Python is better for open source development than Matlab? How curious! :P

**Comment by kcgthb** [comment]
Like maybe we should leave this in, to see if it could work as a subliminal message? :)

**Comment by mpiercy** [comment]
hahah @kcgthb  already did send a reminder- 
"Note: a number of free, open-source alternatives exist and can be used in many situations: Octave, R, Julia, or Python are all available on Sherlock, and can often replace MATLAB with good results."

**Pull request merged**
