### PR TITLE
OnDemand user guide updates for OOD 3.x

### PR DESCRIPTION
**Pull request by cagancayco**

### CODE REVIEW

**Comment by cagancayco** [comment]
started jupyterlab and matlab app documentation

**Comment by cagancayco** [comment]
more documentation!

**Review by kcgthb — APPROVED** [review]
This is absolutely awesome, thank you! 
And thanks for fixing all my typos as well :D

**Review by kcgthb — APPROVED** [review]

**Review by kcgthb — DISMISSED** [review]
Yay, thanks!

**Review by kcgthb — APPROVED** [review]

**Pull request merged**
