### PR TITLE
Update running-jobs.md

### PR DESCRIPTION
**Pull request by mpiercy**
adding example, explanation, terms and concepts for submitting and sbatch jobs

### CODE REVIEW

**Comment by mpiercy** [comment]
will this get reviewed?  its been 19 days 

this is 404 btw- https://app.netlify.com/sites/sherlock-docs-dev/deploys/6206b83bf442d400074a73b7

**Comment by kcgthb** [comment]
Sorry for the delay, previews are now available again: https://deploy-preview-84--sherlock-docs-dev.netlify.app/docs/user-guide/running-jobs/ 
I guess there are some formatting issues. :(

**Comment by mpiercy** [comment]
this is so incredibly frustrating, when I previewed the page on Github it looked fine, I have no idea why it wont render  correctly now I have to do bunch of GitHub BS, and this is just for an HTML doc and not either code nor a config file

**Comment by kcgthb** [comment]
Ok. The GitHub previews are pretty basic, I'm afraid. The best way would probably to follow the workflow described at https://github.com/stanford-rc/www.sherlock.stanford.edu#editing-locally

I'll take a stab at cleaning it.

**Comment by kcgthb** [comment]
This was the reason for the formatting issue:
https://github.com/stanford-rc/www.sherlock.stanford.edu/pull/84/commits/178a2ee4391ae0308b1e6faaf416a47a9d60d331

The documentation for code blocks is at https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#usage

**Review by kcgthb — APPROVED** [review]

**Pull request merged**
