### PR TITLE
adding a note to use the file editor for OOD

### PR DESCRIPTION
**Pull request by mpiercy**
Probably the best use of Sherlock On Demand for brand new users who are freaked out by line oriented editors is the file manager app in Sherlock OnDemand.  Also good for users who get confused with scp/rsync.  Seen a few users in office hours who are very happy to see those features

### CODE REVIEW

**Comment by carolinarsm** [comment]
Just to add a use case from our lab: in neuroimaging there are a number of software pipelines (popular example: fMRIPrep) that output html reports heavy on images files, and on On Demand allows users to check those as they appear on scratch space, for quick QC, instead of having to mount drives, download data locally or move to other storage location. Since the data itself is already quite big and costly to move, On Demand is extremely helpful for fast assessment.

**Comment by kcgthb** [comment]
@carolinarsm awesome to hear! Thanks for sharing this with us.
Would you be ok if we added your testimonial on the Sherlock documentation pages, to illustrate the advantages of OnDemand?

**Comment by carolinarsm** [comment]
@kcgthb sure thing! Efficient visual QC is such a topic in neuroimaging, that it is indeed a huge time saver having the capacity to check as they come in the server (and to get these reports from certain software, credit where is due...)

**Comment by vsoch** [comment]
hey @carolinarsm I tried internet stalking you but I can't figure out what lab you are in?

**Comment by carolinarsm** [comment]
@vsoch I'm at PANLab, with Dr. Williams (I think I never sent my profile or pic for our website, so have 0 internet presence ;) I'm "ramirezc" at Stanford)

**Comment by vsoch** [comment]
Cool thanks :)

**Comment by kcgthb** [comment]
@carolinarsm here's the preview: https://deploy-preview-50--sherlock-docs-dev.netlify.app/docs/user-guide/ondemand/
Please let me know If you're ok with it, and I'll merge it.

**Comment by carolinarsm** [comment]
@kcgthb yes, looks good.

**Pull request merged**
