### PR TITLE
zoom links updated

### PR DESCRIPTION
**Pull request by mpiercy**
had to add passwords to links, even though you already need to be SUNet ID authenticated...

### CODE REVIEW

**Comment by vsoch** [comment]
Are you absolutely sure that's okay to do?

**Comment by kcgthb** [comment]
Yeah, they'll be publicly visible for the whole world to see on the documentation pages, which kind of defeats the purpose of having a password in the first place. Let's discuss this offline.

**Comment by vsoch** [comment]
If it turns out to be a bad idea, probably should reset the ones that are now in git too (or delete the branch) but I'm not sure that would remove them from the PR here.

**Comment by mpiercy** [comment]
forget it, turns out password required only for new meetings.

**Comment by mpiercy** [comment]
anyway all stanford.zoom meetings are behind SUnetID authentication, so passwords are not needed anyway?

**Comment by vsoch** [comment]
I'm not sure that is correct, because I use Zoom for RSE Stories, and many non-Stanford people have joined without a hitch.

**Comment by mpiercy** [comment]
OK, you could be right!
Did you set up those meetings here?
https://stanford.zoom.us/
I thought meetings set-up under the Stanford Zoom account are only accessible after passing in your SUNet ID/passwd credentials.  But I guess if you have a password for the meeting, that is not the case?   I will set up a meeting and test that out.  Clearly I have some zoom studying to do.

**Comment by vsoch** [comment]
I think the login -> create meeting process (which does require a sunetid to do for a Stanford account) is a separate thing from who can use the subsequently generated links. Whether I interact with the stanford interface there, or login directly to zoom with my credentials, the meetings appear in both places (just confirmed this). I think something to test would be checking the box "authenticated users only"

image

But then, what if someone is authenticated via a non-stanford setup? I don't think it's fool proof. I also think it's generally bad practice to put passwords out in the open like that, so I'd push for another means to do it.

**Comment by mpiercy** [comment]
Yep, if you check "only authenticated uses can join" (which I do for office hours), then you need SUnet id to join the meeting and the password is redundant.  That's why I had no prob posting passwd in the clear on the site, I was just thinking to meet new requirements I needed a password.  But in your case you may also want non-Stanford people to join, so you would want a password, and I guess need one, if you make a new meeting after 6/23.

**Pull request closed without merging**
